/**
 * Textes de la commande à table — Joliba
 *
 * À part des textes de la carte (`i18n.ts`) : ils ne sont téléchargés qu'avec le panier, après
 * l'affichage de la carte. Français et anglais, comme la carte (D-050).
 */

import type { GuestLocale } from "./i18n";

const fr = {
  // Paiement en ligne (T5) : le reste des textes vient avec le tiroir
  pay: "Régler",
  payPending: "Paiement en cours",
  // Fiche plat
  quantity: "Quantité",
  less: "Un de moins",
  more: "Un de plus",
  instructions: "Une précision pour la cuisine ?",
  instructionsHint: (n: number) => `Facultatif, ${n} caractères au plus.`,
  chooseVariant: "Choisissez une taille ou une variante.",
  completeChoices: "Complétez vos choix pour ajouter ce plat.",
  unavailable: "Ce plat n'est pas disponible en ce moment.",
  addToCart: (price: string) => `Ajouter · ${price}`,
  cartFull: "Votre panier est plein.",
  cartLocked: "Un envoi attend sa réponse : le panier est bloqué jusque-là.",
  // Commande directe (D-095, D-100)
  sendDirect: "Envoyer — part directement en cuisine",
  sendDirectNote: "La commande part en cuisine dès l'envoi. Vous réglez à la fin du repas.",
  retrySend: "Réessayer l'envoi",
  lockedNote: "L'envoi n'a pas eu de réponse. Le panier reste bloqué : réessayez, la même commande sera retrouvée, jamais envoyée deux fois.",
  sentDirect: (ref: string) => `Commande ${ref} envoyée en cuisine.`,
  codeTitle: "Entrez le code de la table",
  codeText: "Votre serveur le donne à l'arrivée : quatre chiffres, qui changent à chaque tablée.",
  codeLabel: "Code de la table",
  codeWrong: "Ce n'est pas le bon code. Vérifiez-le auprès de votre serveur.",
  codeOk: "C'est bon : vous pouvez envoyer vos commandes.",
  codeOrShow: "Pas de code ? Montrez votre panier au serveur : il peut vous admettre.",
  codeRequired: "Entrez d'abord le code de la table.",
  codeRateLimited: (s: number) => `Trop de codes essayés à cette table. Réessayez dans ${s} s, ou demandez à votre serveur de vous admettre.`,
  showToBeAdmitted: (n: number) => `Vous êtes le convive ${n} : dites ce numéro au serveur s'il vous admet sans le code.`,
  takenChanged: "Votre serveur a déjà pris le panier que vous lui aviez montré (voyez « Mes commandes »). Retirez ce qu'il a pris avant d'envoyer le reste.",
  pendingLost: "Votre envoi n'est pas arrivé : rien n'est parti. Vérifiez votre panier et renvoyez-le.",
  pendingArrived: (ref: string) => `Votre envoi était bien arrivé : commande ${ref}.`,
  shownExpired: "Votre panier montré a expiré sans être pris. Montrez-le de nouveau si besoin.",
  lineHeld: "Attend son tour — partira au bon moment",
  tableCode: "Code de la table",
  shareCode: "Donnez-le à ceux qui vous rejoignent.",
  youAreGuest: (n: number) => `Vous êtes le convive ${n}`,
  removedTitle: "Ce téléphone a été retiré de la table",
  removedText: "Il ne peut plus envoyer de commande. Appelez un serveur si c'est une erreur.",
  tooMany: (max: number) => `${max} au plus par plat et par envoi.`,
  tooManyLines: "Trop de plats différents pour un seul envoi : envoyez en deux fois.",
  // Suivi (D-103)
  takenByWaiter: "Pris par votre serveur",
  lineOrdered: "Envoyé en cuisine",
  linePreparing: "En préparation",
  lineReady: "Prêt — on vous l'apporte",
  lineServed: "Servi",
  lineCancelled: "Annulé par le restaurant — parlez-en à votre serveur",
  sentAgo: (d: string) => `envoyée il y a ${d}`,
  updatedAgo: (s: number) => (s < 5 ? "Mis à jour à l'instant" : `Mis à jour il y a ${s < 60 ? `${s} s` : `${Math.floor(s / 60)} min`}`),
  tabMine: "Mes commandes",
  tabTable: "La table",
  tableTitle: "Ce que la table a commandé",
  tableNote: "Ce qui est déjà parti pour toute la tablée, pour ne pas commander deux fois.",
  tableEmpty: "Rien n'est encore parti pour la table.",
  guestN: (n: number) => `Convive ${n}`,
  you: "Vous",
  byWaiter: "Serveur",
  // Avis (D-105)
  feedbackCta: "Donner mon avis",
  feedbackTitle: "Votre avis sur le repas",
  feedbackDescription: "Il va au restaurant, et à lui seul.",
  ratingLabel: "Votre note",
  rating: (n: number) => `${n} sur 5`,
  topicsLabel: "Ce qui a compté (facultatif)",
  topics: { accueil: "Accueil", attente: "Attente", plats: "Plats", boissons: "Boissons", proprete: "Propreté", prix: "Prix" } as Record<string, string>,
  commentLabel: "Un mot (facultatif)",
  commentHint: "N'y mettez pas vos coordonnées.",
  feedbackSend: "Envoyer mon avis",
  feedbackThanks: "Merci pour votre avis.",
  feedbackTooLate: "Le délai pour donner un avis est passé.",
  chooseRating: "Choisissez une note.",
  // Barre
  myCart: "Mon panier",
  items: (n: number) => (n <= 1 ? `${n} article` : `${n} articles`),
  call: "Appeler",
  myOrders: "Mes commandes",
  // Panier
  cartTitle: "Mon panier",
  cartEmpty: "Votre panier est vide. Touchez un plat pour l'ajouter.",
  estimatedTotal: "Total estimé",
  priceNote: "Prix indicatifs : le montant qui fait foi est celui de votre serveur.",
  remove: "Retirer",
  showWaiter: "Montrer au serveur",
  showAgain: "Montrer de nouveau",
  shownTitle: "Panier prêt — montrez-le à votre serveur",
  shownText: "Rien n'est commandé. Votre serveur voit ce panier sur sa tablette et le valide avec vous.",
  changedSinceShown: "Vous avez modifié le panier : montrez-le de nouveau pour que le serveur voie la dernière version.",
  send: "Envoyer la commande",
  sendNote: "Votre commande sera validée par un serveur avant de partir en cuisine.",
  tableClosedTitle: "Votre table n'est pas encore ouverte",
  tableClosedText: "Un serveur l'ouvrira à son arrivée. Vous pouvez déjà composer votre panier, ou l'appeler.",
  offlineSend: "Pas de réseau : votre panier est gardé sur ce téléphone. Réessayez dès que le réseau revient.",
  noPass: "Votre accès à la table a expiré. Scannez de nouveau le QR code de la table.",
  networkError: "Le réseau ne répond pas. Votre panier est gardé : réessayez.",
  full: "Trop de téléphones à cette table. Demandez à votre serveur.",
  rateLimited: (s: number) => `Trop d'envois depuis cette table. Réessayez dans ${s} s.`,
  problemsRemoved: "Certains plats ne sont plus disponibles ; retirez-les pour continuer.",
  importedByWaiter: "Panier pris par votre serveur : il est dans « Mes commandes ».",
  dismissedByWaiter: "Votre panier n'est plus affiché chez le serveur. Montrez-le de nouveau si besoin.",
  // Commandes
  ordersTitle: "Mes commandes",
  ordersEmpty: "Aucune commande pour l'instant.",
  statusPending: "En attente de validation",
  statusPendingText: "Pas encore en cuisine : un serveur doit la valider.",
  statusAccepted: "Acceptée",
  statusRejected: "Refusée",
  statusExpired: "Expirée",
  statusExpiredText: "Personne n'a pu la valider à temps. Appelez un serveur.",
  statusCancelled: "Annulée",
  statusInPreparation: "En préparation",
  statusReady: "Prête",
  statusServed: "Servie",
  reason: "Motif",
  order: (ref: string) => `Commande ${ref}`,
  sent: (ref: string) => `Commande ${ref} envoyée — en attente de validation par un serveur.`,
  // Appeler
  callTitle: "Appeler",
  callDescription: "Un serveur sera prévenu à votre table.",
  requestSent: "Demande envoyée — un serveur arrive.",
  alreadyAsked: "Déjà demandé — un serveur a été prévenu.",
  waitBefore: (m: string) => `Déjà demandé · de nouveau possible dans ${m}`,
  duration: (seconds: number) => (seconds < 60 ? `${seconds} s` : `${Math.ceil(seconds / 60)} min`),
  noRequestTypes: "Faites signe à un serveur.",
  loading: "Chargement…",
  close: "Fermer",
  added: (name: string) => `${name} ajouté au panier`,
};

type OrderText = typeof fr;

const en: OrderText = {
  pay: "Pay",
  payPending: "Payment in progress",
  quantity: "Quantity",
  less: "One less",
  more: "One more",
  instructions: "A note for the kitchen?",
  instructionsHint: (n: number) => `Optional, up to ${n} characters.`,
  chooseVariant: "Choose a size or a variant.",
  completeChoices: "Complete your choices to add this dish.",
  unavailable: "This dish is not available right now.",
  addToCart: (price: string) => `Add · ${price}`,
  cartFull: "Your cart is full.",
  cartLocked: "A send is waiting for its answer: the cart is locked until then.",
  sendDirect: "Send — goes straight to the kitchen",
  sendDirectNote: "Your order goes to the kitchen as soon as you send it. You pay at the end of the meal.",
  retrySend: "Try sending again",
  lockedNote: "The send got no answer. The cart stays locked: try again, the same order will be found, never sent twice.",
  sentDirect: (ref: string) => `Order ${ref} sent to the kitchen.`,
  codeTitle: "Enter the table code",
  codeText: "Your waiter gives it when you arrive: four digits, new for every party.",
  codeLabel: "Table code",
  codeWrong: "That is not the right code. Check it with your waiter.",
  codeOk: "All set: you can send your orders.",
  codeOrShow: "No code? Show your cart to the waiter: they can let you in.",
  codeRequired: "Enter the table code first.",
  codeRateLimited: (s: number) => `Too many codes tried at this table. Try again in ${s} s, or ask your waiter to let you in.`,
  showToBeAdmitted: (n: number) => `You are guest ${n}: tell your waiter this number if they let you in without the code.`,
  takenChanged: "Your waiter already took the cart you showed them (see “My orders”). Remove what they took before sending the rest.",
  pendingLost: "Your send did not arrive: nothing went out. Check your cart and send it again.",
  pendingArrived: (ref: string) => `Your send had arrived: order ${ref}.`,
  shownExpired: "The cart you showed expired without being taken. Show it again if needed.",
  lineHeld: "Waiting for its course — will go out at the right time",
  tableCode: "Table code",
  shareCode: "Give it to those who join you.",
  youAreGuest: (n: number) => `You are guest ${n}`,
  removedTitle: "This phone was removed from the table",
  removedText: "It can no longer send orders. Call a waiter if this is a mistake.",
  tooMany: (max: number) => `${max} at most per dish in one send.`,
  tooManyLines: "Too many different dishes for one send: send in two goes.",
  takenByWaiter: "Taken by your waiter",
  lineOrdered: "Sent to the kitchen",
  linePreparing: "Being prepared",
  lineReady: "Ready — on its way",
  lineServed: "Served",
  lineCancelled: "Cancelled by the restaurant — ask your waiter",
  sentAgo: (d: string) => `sent ${d} ago`,
  updatedAgo: (s: number) => (s < 5 ? "Updated just now" : `Updated ${s < 60 ? `${s} s` : `${Math.floor(s / 60)} min`} ago`),
  tabMine: "My orders",
  tabTable: "The table",
  tableTitle: "What the table ordered",
  tableNote: "What has already gone out for the whole party, so nobody orders twice.",
  tableEmpty: "Nothing has gone out for the table yet.",
  guestN: (n: number) => `Guest ${n}`,
  you: "You",
  byWaiter: "Waiter",
  feedbackCta: "Give feedback",
  feedbackTitle: "Your feedback on the meal",
  feedbackDescription: "It goes to the restaurant, and to them only.",
  ratingLabel: "Your rating",
  rating: (n: number) => `${n} out of 5`,
  topicsLabel: "What mattered (optional)",
  topics: { accueil: "Welcome", attente: "Waiting time", plats: "Food", boissons: "Drinks", proprete: "Cleanliness", prix: "Prices" } as Record<string, string>,
  commentLabel: "A few words (optional)",
  commentHint: "Do not include your contact details.",
  feedbackSend: "Send my feedback",
  feedbackThanks: "Thank you for your feedback.",
  feedbackTooLate: "The time to give feedback has passed.",
  chooseRating: "Choose a rating.",
  myCart: "My cart",
  items: (n: number) => (n <= 1 ? `${n} item` : `${n} items`),
  call: "Call",
  myOrders: "My orders",
  cartTitle: "My cart",
  cartEmpty: "Your cart is empty. Tap a dish to add it.",
  estimatedTotal: "Estimated total",
  priceNote: "Prices are indicative: your waiter's bill is the one that counts.",
  remove: "Remove",
  showWaiter: "Show my waiter",
  showAgain: "Show again",
  shownTitle: "Cart ready — show it to your waiter",
  shownText: "Nothing is ordered yet. Your waiter sees this cart on their tablet and confirms it with you.",
  changedSinceShown: "You changed the cart: show it again so your waiter sees the latest version.",
  send: "Send my order",
  sendNote: "A waiter will confirm your order before it goes to the kitchen.",
  tableClosedTitle: "Your table is not open yet",
  tableClosedText: "A waiter will open it when they come by. You can already fill your cart, or call them.",
  offlineSend: "No network: your cart is kept on this phone. Try again when the network is back.",
  noPass: "Your table access has expired. Scan the table's QR code again.",
  networkError: "The network is not responding. Your cart is kept: try again.",
  full: "Too many phones at this table. Ask your waiter.",
  rateLimited: (s: number) => `Too many requests from this table. Try again in ${s} s.`,
  problemsRemoved: "Some dishes are no longer available; remove them to continue.",
  importedByWaiter: "Your waiter took your cart: see “My orders”.",
  dismissedByWaiter: "Your cart is no longer shown to the waiter. Show it again if needed.",
  ordersTitle: "My orders",
  ordersEmpty: "No order yet.",
  statusPending: "Waiting for approval",
  statusPendingText: "Not in the kitchen yet: a waiter must confirm it.",
  statusAccepted: "Accepted",
  statusRejected: "Declined",
  statusExpired: "Expired",
  statusExpiredText: "Nobody could confirm it in time. Call a waiter.",
  statusCancelled: "Cancelled",
  statusInPreparation: "Being prepared",
  statusReady: "Ready",
  statusServed: "Served",
  reason: "Reason",
  order: (ref: string) => `Order ${ref}`,
  sent: (ref: string) => `Order ${ref} sent — waiting for a waiter to confirm it.`,
  callTitle: "Call",
  callDescription: "A waiter will be notified at your table.",
  requestSent: "Request sent — a waiter is coming.",
  alreadyAsked: "Already requested — a waiter has been notified.",
  waitBefore: (m: string) => `Already requested · available again in ${m}`,
  duration: (seconds: number) => (seconds < 60 ? `${seconds} s` : `${Math.ceil(seconds / 60)} min`),
  noRequestTypes: "Wave to a waiter.",
  loading: "Loading…",
  close: "Close",
  added: (name: string) => `${name} added to cart`,
};

export const ORDER_TEXT: Record<GuestLocale, OrderText> = { fr, en };
export type { OrderText };
