/**
 * Textes de la commande à table — Joliba
 *
 * À part des textes de la carte (`i18n.ts`) : ils ne sont téléchargés qu'avec le panier, après
 * l'affichage de la carte. Français et anglais, comme la carte (D-050).
 */

import type { GuestLocale } from "./i18n";

const fr = {
  // Fiche plat
  quantity: "Quantité",
  less: "Un de moins",
  more: "Un de plus",
  instructions: "Une précision pour la cuisine ?",
  instructionsHint: (n: number) => `Facultatif, ${n} caractères au plus.`,
  chooseVariant: "Choisissez une taille ou une variante.",
  completeChoices: "Complétez vos choix pour ajouter ce plat.",
  unavailable: "Ce plat n'est pas disponible en ce moment.",
  addToCart: (price: string) => `Ajouter · ${price}`,
  cartFull: "Votre panier est plein.",
  // Barre
  myCart: "Mon panier",
  items: (n: number) => (n <= 1 ? `${n} article` : `${n} articles`),
  call: "Appeler",
  myOrders: "Mes commandes",
  // Panier
  cartTitle: "Mon panier",
  cartEmpty: "Votre panier est vide. Touchez un plat pour l'ajouter.",
  estimatedTotal: "Total estimé",
  priceNote: "Prix indicatifs : le montant qui fait foi est celui de votre serveur.",
  remove: "Retirer",
  showWaiter: "Montrer au serveur",
  showAgain: "Montrer de nouveau",
  shownTitle: "Panier prêt — montrez-le à votre serveur",
  shownText: "Rien n'est commandé. Votre serveur voit ce panier sur sa tablette et le valide avec vous.",
  changedSinceShown: "Vous avez modifié le panier : montrez-le de nouveau pour que le serveur voie la dernière version.",
  send: "Envoyer la commande",
  sendNote: "Votre commande sera validée par un serveur avant de partir en cuisine.",
  tableClosedTitle: "Votre table n'est pas encore ouverte",
  tableClosedText: "Un serveur l'ouvrira à son arrivée. Vous pouvez déjà composer votre panier, ou l'appeler.",
  offlineSend: "Pas de réseau : votre panier est gardé sur ce téléphone. Réessayez dès que le réseau revient.",
  noPass: "Votre accès à la table a expiré. Scannez de nouveau le QR code de la table.",
  networkError: "Le réseau ne répond pas. Votre panier est gardé : réessayez.",
  full: "Trop de téléphones à cette table. Demandez à votre serveur.",
  rateLimited: (s: number) => `Trop d'envois depuis cette table. Réessayez dans ${s} s.`,
  problemsRemoved: "Certains plats ne sont plus disponibles ; retirez-les pour continuer.",
  importedByWaiter: "Votre serveur a pris votre panier : il est dans « Mes commandes ».",
  dismissedByWaiter: "Votre panier n'est plus affiché chez le serveur. Montrez-le de nouveau si besoin.",
  // Commandes
  ordersTitle: "Mes commandes",
  ordersEmpty: "Aucune commande pour l'instant.",
  statusPending: "En attente de validation",
  statusPendingText: "Pas encore en cuisine : un serveur doit la valider.",
  statusAccepted: "Acceptée",
  statusRejected: "Refusée",
  statusExpired: "Expirée",
  statusExpiredText: "Personne n'a pu la valider à temps. Appelez un serveur.",
  statusCancelled: "Annulée",
  statusInPreparation: "En préparation",
  statusReady: "Prête",
  statusServed: "Servie",
  reason: "Motif",
  order: (ref: string) => `Commande ${ref}`,
  sent: (ref: string) => `Commande ${ref} envoyée — en attente de validation par un serveur.`,
  // Appeler
  callTitle: "Appeler",
  callDescription: "Un serveur sera prévenu à votre table.",
  requestSent: "Demande envoyée — un serveur arrive.",
  alreadyAsked: "Déjà demandé — un serveur a été prévenu.",
  waitBefore: (m: string) => `Déjà demandé · de nouveau possible dans ${m}`,
  duration: (seconds: number) => (seconds < 60 ? `${seconds} s` : `${Math.ceil(seconds / 60)} min`),
  noRequestTypes: "Faites signe à un serveur.",
  loading: "Chargement…",
  close: "Fermer",
  added: (name: string) => `${name} ajouté au panier`,
};

type OrderText = typeof fr;

const en: OrderText = {
  quantity: "Quantity",
  less: "One less",
  more: "One more",
  instructions: "A note for the kitchen?",
  instructionsHint: (n: number) => `Optional, up to ${n} characters.`,
  chooseVariant: "Choose a size or a variant.",
  completeChoices: "Complete your choices to add this dish.",
  unavailable: "This dish is not available right now.",
  addToCart: (price: string) => `Add · ${price}`,
  cartFull: "Your cart is full.",
  myCart: "My cart",
  items: (n: number) => (n <= 1 ? `${n} item` : `${n} items`),
  call: "Call",
  myOrders: "My orders",
  cartTitle: "My cart",
  cartEmpty: "Your cart is empty. Tap a dish to add it.",
  estimatedTotal: "Estimated total",
  priceNote: "Prices are indicative: your waiter's bill is the one that counts.",
  remove: "Remove",
  showWaiter: "Show my waiter",
  showAgain: "Show again",
  shownTitle: "Cart ready — show it to your waiter",
  shownText: "Nothing is ordered yet. Your waiter sees this cart on their tablet and confirms it with you.",
  changedSinceShown: "You changed the cart: show it again so your waiter sees the latest version.",
  send: "Send my order",
  sendNote: "A waiter will confirm your order before it goes to the kitchen.",
  tableClosedTitle: "Your table is not open yet",
  tableClosedText: "A waiter will open it when they come by. You can already fill your cart, or call them.",
  offlineSend: "No network: your cart is kept on this phone. Try again when the network is back.",
  noPass: "Your table access has expired. Scan the table's QR code again.",
  networkError: "The network is not responding. Your cart is kept: try again.",
  full: "Too many phones at this table. Ask your waiter.",
  rateLimited: (s: number) => `Too many requests from this table. Try again in ${s} s.`,
  problemsRemoved: "Some dishes are no longer available; remove them to continue.",
  importedByWaiter: "Your waiter took your cart: see “My orders”.",
  dismissedByWaiter: "Your cart is no longer shown to the waiter. Show it again if needed.",
  ordersTitle: "My orders",
  ordersEmpty: "No order yet.",
  statusPending: "Waiting for approval",
  statusPendingText: "Not in the kitchen yet: a waiter must confirm it.",
  statusAccepted: "Accepted",
  statusRejected: "Declined",
  statusExpired: "Expired",
  statusExpiredText: "Nobody could confirm it in time. Call a waiter.",
  statusCancelled: "Cancelled",
  statusInPreparation: "Being prepared",
  statusReady: "Ready",
  statusServed: "Served",
  reason: "Reason",
  order: (ref: string) => `Order ${ref}`,
  sent: (ref: string) => `Order ${ref} sent — waiting for a waiter to confirm it.`,
  callTitle: "Call",
  callDescription: "A waiter will be notified at your table.",
  requestSent: "Request sent — a waiter is coming.",
  alreadyAsked: "Already requested — a waiter has been notified.",
  waitBefore: (m: string) => `Already requested · available again in ${m}`,
  duration: (seconds: number) => (seconds < 60 ? `${seconds} s` : `${Math.ceil(seconds / 60)} min`),
  noRequestTypes: "Wave to a waiter.",
  loading: "Loading…",
  close: "Close",
  added: (name: string) => `${name} added to cart`,
};

export const ORDER_TEXT: Record<GuestLocale, OrderText> = { fr, en };
export type { OrderText };
