/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ApiClientErrorsRouteImport } from './routes/api/client-errors'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppRolesIndexRouteImport } from './routes/app.roles.index'
import { Route as AppRolesRoleIdRouteImport } from './routes/app.roles.$roleId'
import { Route as AppSettingsVenueRouteImport } from './routes/app.settings.venue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientErrorsRoute = ApiClientErrorsRouteImport.update({
  id: '/api/client-errors',
  path: '/api/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsVenueRoute = AppSettingsVenueRouteImport.update({
  id: '/settings/venue',
  path: '/settings/venue',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/team': typeof AppTeamRoute
  '/auth/otp': typeof AuthOtpRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/settings/venue': typeof AppSettingsVenueRoute
  '/app/roles/': typeof AppRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/team': typeof AppTeamRoute
  '/auth/otp': typeof AuthOtpRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/settings/venue': typeof AppSettingsVenueRoute
  '/app/roles': typeof AppRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/team': typeof AppTeamRoute
  '/auth/otp': typeof AuthOtpRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/app/settings/venue': typeof AppSettingsVenueRoute
  '/app/roles/': typeof AppRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/app/account'
    | '/app/onboarding'
    | '/app/team'
    | '/auth/otp'
    | '/invitation/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/roles/$roleId'
    | '/app/settings/venue'
    | '/app/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/app/account'
    | '/app/onboarding'
    | '/app/team'
    | '/auth/otp'
    | '/invitation/$token'
    | '/app'
    | '/api/auth/$'
    | '/app/roles/$roleId'
    | '/app/settings/venue'
    | '/app/roles'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/app/account'
    | '/app/onboarding'
    | '/app/team'
    | '/auth/otp'
    | '/invitation/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/roles/$roleId'
    | '/app/settings/venue'
    | '/app/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ApiClientErrorsRoute: typeof ApiClientErrorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthOtpRoute: typeof AuthOtpRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-errors': {
      id: '/api/client-errors'
      path: '/api/client-errors'
      fullPath: '/api/client-errors'
      preLoaderRoute: typeof ApiClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/roles/': {
      id: '/app/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles/$roleId': {
      id: '/app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/app/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/venue': {
      id: '/app/settings/venue'
      path: '/settings/venue'
      fullPath: '/app/settings/venue'
      preLoaderRoute: typeof AppSettingsVenueRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppSettingsVenueRoute: typeof AppSettingsVenueRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppSettingsVenueRoute: AppSettingsVenueRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ApiClientErrorsRoute: ApiClientErrorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthOtpRoute: AuthOtpRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
