/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppareilRouteImport } from './routes/appareil'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthAppRouteImport } from './routes/_auth.app'
import { Route as AuthConnexionRouteImport } from './routes/_auth.connexion'
import { Route as ApiClientErrorsRouteImport } from './routes/api/client-errors'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppareilIndexRouteImport } from './routes/appareil.index'
import { Route as AppareilCaisseRouteImport } from './routes/appareil.caisse'
import { Route as MenuVenueSlugRouteImport } from './routes/menu.$venueSlug'
import { Route as AuthAppIndexRouteImport } from './routes/_auth.app.index'
import { Route as AuthAppAccountRouteImport } from './routes/_auth.app.account'
import { Route as AuthAppAnalyticsRouteImport } from './routes/_auth.app.analytics'
import { Route as AuthAppCuisineRouteImport } from './routes/_auth.app.cuisine'
import { Route as AuthAppFeedbackRouteImport } from './routes/_auth.app.feedback'
import { Route as AuthAppMenuRouteImport } from './routes/_auth.app.menu'
import { Route as AuthAppOnboardingRouteImport } from './routes/_auth.app.onboarding'
import { Route as AuthAppRapportRouteImport } from './routes/_auth.app.rapport'
import { Route as AuthAppServiceRouteImport } from './routes/_auth.app.service'
import { Route as AuthAppTeamRouteImport } from './routes/_auth.app.team'
import { Route as AuthAuthOtpRouteImport } from './routes/_auth.auth.otp'
import { Route as AuthInvitationTokenRouteImport } from './routes/_auth.invitation.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppareilTableTableIdRouteImport } from './routes/appareil.table.$tableId'
import { Route as RVenueSlugIndisponibleRouteImport } from './routes/r.$venueSlug.indisponible'
import { Route as RVenueSlugTableRouteImport } from './routes/r.$venueSlug.table'
import { Route as AuthAppFloorIndexRouteImport } from './routes/_auth.app.floor.index'
import { Route as AuthAppFloorPrintRouteImport } from './routes/_auth.app.floor.print'
import { Route as AuthAppMenuIndexRouteImport } from './routes/_auth.app.menu.index'
import { Route as AuthAppMenuAvailabilityRouteImport } from './routes/_auth.app.menu.availability'
import { Route as AuthAppMenuCategoriesRouteImport } from './routes/_auth.app.menu.categories'
import { Route as AuthAppMenuOptionsRouteImport } from './routes/_auth.app.menu.options'
import { Route as AuthAppRolesIndexRouteImport } from './routes/_auth.app.roles.index'
import { Route as AuthAppRolesRoleIdRouteImport } from './routes/_auth.app.roles.$roleId'
import { Route as AuthAppServiceIndexRouteImport } from './routes/_auth.app.service.index'
import { Route as AuthAppServiceCaisseRouteImport } from './routes/_auth.app.service.caisse'
import { Route as AuthAppSettingsDevicesRouteImport } from './routes/_auth.app.settings.devices'
import { Route as AuthAppSettingsPaymentsRouteImport } from './routes/_auth.app.settings.payments'
import { Route as AuthAppSettingsStationsRouteImport } from './routes/_auth.app.settings.stations'
import { Route as AuthAppSettingsVenueRouteImport } from './routes/_auth.app.settings.venue'
import { Route as RVenueSlugTTokenRouteImport } from './routes/r.$venueSlug.t.$token'
import { Route as AuthAppMenuProductsIndexRouteImport } from './routes/_auth.app.menu.products.index'
import { Route as AuthAppMenuProductsProductIdRouteImport } from './routes/_auth.app.menu.products.$productId'
import { Route as AuthAppServiceTableTableIdRouteImport } from './routes/_auth.app.service.table.$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppareilRoute = AppareilRouteImport.update({
  id: '/appareil',
  path: '/appareil',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => AuthRoute,
} as any)
const ApiClientErrorsRoute = ApiClientErrorsRouteImport.update({
  id: '/api/client-errors',
  path: '/api/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppareilIndexRoute = AppareilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppareilRoute,
} as any)
const AppareilCaisseRoute = AppareilCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AppareilRoute,
} as any)
const MenuVenueSlugRoute = MenuVenueSlugRouteImport.update({
  id: '/menu/$venueSlug',
  path: '/menu/$venueSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAccountRoute = AuthAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAnalyticsRoute = AuthAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppCuisineRoute = AuthAppCuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppFeedbackRoute = AuthAppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppMenuRoute = AuthAppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppOnboardingRoute = AuthAppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppRapportRoute = AuthAppRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppServiceRoute = AuthAppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppTeamRoute = AuthAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAuthOtpRoute = AuthAuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvitationTokenRoute = AuthInvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppareilTableTableIdRoute = AppareilTableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => AppareilRoute,
} as any)
const RVenueSlugIndisponibleRoute = RVenueSlugIndisponibleRouteImport.update({
  id: '/r/$venueSlug/indisponible',
  path: '/r/$venueSlug/indisponible',
  getParentRoute: () => rootRouteImport,
} as any)
const RVenueSlugTableRoute = RVenueSlugTableRouteImport.update({
  id: '/r/$venueSlug/table',
  path: '/r/$venueSlug/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppFloorIndexRoute = AuthAppFloorIndexRouteImport.update({
  id: '/floor/',
  path: '/floor/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppFloorPrintRoute = AuthAppFloorPrintRouteImport.update({
  id: '/floor/print',
  path: '/floor/print',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppMenuIndexRoute = AuthAppMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppMenuRoute,
} as any)
const AuthAppMenuAvailabilityRoute = AuthAppMenuAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AuthAppMenuRoute,
} as any)
const AuthAppMenuCategoriesRoute = AuthAppMenuCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthAppMenuRoute,
} as any)
const AuthAppMenuOptionsRoute = AuthAppMenuOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AuthAppMenuRoute,
} as any)
const AuthAppRolesIndexRoute = AuthAppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppRolesRoleIdRoute = AuthAppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppServiceIndexRoute = AuthAppServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppServiceRoute,
} as any)
const AuthAppServiceCaisseRoute = AuthAppServiceCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthAppServiceRoute,
} as any)
const AuthAppSettingsDevicesRoute = AuthAppSettingsDevicesRouteImport.update({
  id: '/settings/devices',
  path: '/settings/devices',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSettingsPaymentsRoute = AuthAppSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSettingsStationsRoute = AuthAppSettingsStationsRouteImport.update({
  id: '/settings/stations',
  path: '/settings/stations',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSettingsVenueRoute = AuthAppSettingsVenueRouteImport.update({
  id: '/settings/venue',
  path: '/settings/venue',
  getParentRoute: () => AuthAppRoute,
} as any)
const RVenueSlugTTokenRoute = RVenueSlugTTokenRouteImport.update({
  id: '/r/$venueSlug/t/$token',
  path: '/r/$venueSlug/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppMenuProductsIndexRoute =
  AuthAppMenuProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthAppMenuRoute,
  } as any)
const AuthAppMenuProductsProductIdRoute =
  AuthAppMenuProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthAppMenuRoute,
  } as any)
const AuthAppServiceTableTableIdRoute =
  AuthAppServiceTableTableIdRouteImport.update({
    id: '/table/$tableId',
    path: '/table/$tableId',
    getParentRoute: () => AuthAppServiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appareil': typeof AppareilRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthAppRouteWithChildren
  '/connexion': typeof AuthConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/appareil/caisse': typeof AppareilCaisseRoute
  '/menu/$venueSlug': typeof MenuVenueSlugRoute
  '/appareil/': typeof AppareilIndexRoute
  '/app/account': typeof AuthAppAccountRoute
  '/app/analytics': typeof AuthAppAnalyticsRoute
  '/app/cuisine': typeof AuthAppCuisineRoute
  '/app/feedback': typeof AuthAppFeedbackRoute
  '/app/menu': typeof AuthAppMenuRouteWithChildren
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/app/rapport': typeof AuthAppRapportRoute
  '/app/service': typeof AuthAppServiceRouteWithChildren
  '/app/team': typeof AuthAppTeamRoute
  '/auth/otp': typeof AuthAuthOtpRoute
  '/invitation/$token': typeof AuthInvitationTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appareil/table/$tableId': typeof AppareilTableTableIdRoute
  '/r/$venueSlug/indisponible': typeof RVenueSlugIndisponibleRoute
  '/r/$venueSlug/table': typeof RVenueSlugTableRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/floor/print': typeof AuthAppFloorPrintRoute
  '/app/menu/availability': typeof AuthAppMenuAvailabilityRoute
  '/app/menu/categories': typeof AuthAppMenuCategoriesRoute
  '/app/menu/options': typeof AuthAppMenuOptionsRoute
  '/app/roles/$roleId': typeof AuthAppRolesRoleIdRoute
  '/app/service/caisse': typeof AuthAppServiceCaisseRoute
  '/app/settings/devices': typeof AuthAppSettingsDevicesRoute
  '/app/settings/payments': typeof AuthAppSettingsPaymentsRoute
  '/app/settings/stations': typeof AuthAppSettingsStationsRoute
  '/app/settings/venue': typeof AuthAppSettingsVenueRoute
  '/r/$venueSlug/t/$token': typeof RVenueSlugTTokenRoute
  '/app/floor/': typeof AuthAppFloorIndexRoute
  '/app/menu/': typeof AuthAppMenuIndexRoute
  '/app/roles/': typeof AuthAppRolesIndexRoute
  '/app/service/': typeof AuthAppServiceIndexRoute
  '/app/menu/products/$productId': typeof AuthAppMenuProductsProductIdRoute
  '/app/service/table/$tableId': typeof AuthAppServiceTableTableIdRoute
  '/app/menu/products/': typeof AuthAppMenuProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/connexion': typeof AuthConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/appareil/caisse': typeof AppareilCaisseRoute
  '/menu/$venueSlug': typeof MenuVenueSlugRoute
  '/appareil': typeof AppareilIndexRoute
  '/app/account': typeof AuthAppAccountRoute
  '/app/analytics': typeof AuthAppAnalyticsRoute
  '/app/cuisine': typeof AuthAppCuisineRoute
  '/app/feedback': typeof AuthAppFeedbackRoute
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/app/rapport': typeof AuthAppRapportRoute
  '/app/team': typeof AuthAppTeamRoute
  '/auth/otp': typeof AuthAuthOtpRoute
  '/invitation/$token': typeof AuthInvitationTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appareil/table/$tableId': typeof AppareilTableTableIdRoute
  '/r/$venueSlug/indisponible': typeof RVenueSlugIndisponibleRoute
  '/r/$venueSlug/table': typeof RVenueSlugTableRoute
  '/app': typeof AuthAppIndexRoute
  '/app/floor/print': typeof AuthAppFloorPrintRoute
  '/app/menu/availability': typeof AuthAppMenuAvailabilityRoute
  '/app/menu/categories': typeof AuthAppMenuCategoriesRoute
  '/app/menu/options': typeof AuthAppMenuOptionsRoute
  '/app/roles/$roleId': typeof AuthAppRolesRoleIdRoute
  '/app/service/caisse': typeof AuthAppServiceCaisseRoute
  '/app/settings/devices': typeof AuthAppSettingsDevicesRoute
  '/app/settings/payments': typeof AuthAppSettingsPaymentsRoute
  '/app/settings/stations': typeof AuthAppSettingsStationsRoute
  '/app/settings/venue': typeof AuthAppSettingsVenueRoute
  '/r/$venueSlug/t/$token': typeof RVenueSlugTTokenRoute
  '/app/floor': typeof AuthAppFloorIndexRoute
  '/app/menu': typeof AuthAppMenuIndexRoute
  '/app/roles': typeof AuthAppRolesIndexRoute
  '/app/service': typeof AuthAppServiceIndexRoute
  '/app/menu/products/$productId': typeof AuthAppMenuProductsProductIdRoute
  '/app/service/table/$tableId': typeof AuthAppServiceTableTableIdRoute
  '/app/menu/products': typeof AuthAppMenuProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/appareil': typeof AppareilRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/connexion': typeof AuthConnexionRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/health': typeof ApiHealthRoute
  '/appareil/caisse': typeof AppareilCaisseRoute
  '/menu/$venueSlug': typeof MenuVenueSlugRoute
  '/appareil/': typeof AppareilIndexRoute
  '/_auth/app/account': typeof AuthAppAccountRoute
  '/_auth/app/analytics': typeof AuthAppAnalyticsRoute
  '/_auth/app/cuisine': typeof AuthAppCuisineRoute
  '/_auth/app/feedback': typeof AuthAppFeedbackRoute
  '/_auth/app/menu': typeof AuthAppMenuRouteWithChildren
  '/_auth/app/onboarding': typeof AuthAppOnboardingRoute
  '/_auth/app/rapport': typeof AuthAppRapportRoute
  '/_auth/app/service': typeof AuthAppServiceRouteWithChildren
  '/_auth/app/team': typeof AuthAppTeamRoute
  '/_auth/auth/otp': typeof AuthAuthOtpRoute
  '/_auth/invitation/$token': typeof AuthInvitationTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/appareil/table/$tableId': typeof AppareilTableTableIdRoute
  '/r/$venueSlug/indisponible': typeof RVenueSlugIndisponibleRoute
  '/r/$venueSlug/table': typeof RVenueSlugTableRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/floor/print': typeof AuthAppFloorPrintRoute
  '/_auth/app/menu/availability': typeof AuthAppMenuAvailabilityRoute
  '/_auth/app/menu/categories': typeof AuthAppMenuCategoriesRoute
  '/_auth/app/menu/options': typeof AuthAppMenuOptionsRoute
  '/_auth/app/roles/$roleId': typeof AuthAppRolesRoleIdRoute
  '/_auth/app/service/caisse': typeof AuthAppServiceCaisseRoute
  '/_auth/app/settings/devices': typeof AuthAppSettingsDevicesRoute
  '/_auth/app/settings/payments': typeof AuthAppSettingsPaymentsRoute
  '/_auth/app/settings/stations': typeof AuthAppSettingsStationsRoute
  '/_auth/app/settings/venue': typeof AuthAppSettingsVenueRoute
  '/r/$venueSlug/t/$token': typeof RVenueSlugTTokenRoute
  '/_auth/app/floor/': typeof AuthAppFloorIndexRoute
  '/_auth/app/menu/': typeof AuthAppMenuIndexRoute
  '/_auth/app/roles/': typeof AuthAppRolesIndexRoute
  '/_auth/app/service/': typeof AuthAppServiceIndexRoute
  '/_auth/app/menu/products/$productId': typeof AuthAppMenuProductsProductIdRoute
  '/_auth/app/service/table/$tableId': typeof AuthAppServiceTableTableIdRoute
  '/_auth/app/menu/products/': typeof AuthAppMenuProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appareil'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app'
    | '/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/appareil/caisse'
    | '/menu/$venueSlug'
    | '/appareil/'
    | '/app/account'
    | '/app/analytics'
    | '/app/cuisine'
    | '/app/feedback'
    | '/app/menu'
    | '/app/onboarding'
    | '/app/rapport'
    | '/app/service'
    | '/app/team'
    | '/auth/otp'
    | '/invitation/$token'
    | '/api/auth/$'
    | '/appareil/table/$tableId'
    | '/r/$venueSlug/indisponible'
    | '/r/$venueSlug/table'
    | '/app/'
    | '/app/floor/print'
    | '/app/menu/availability'
    | '/app/menu/categories'
    | '/app/menu/options'
    | '/app/roles/$roleId'
    | '/app/service/caisse'
    | '/app/settings/devices'
    | '/app/settings/payments'
    | '/app/settings/stations'
    | '/app/settings/venue'
    | '/r/$venueSlug/t/$token'
    | '/app/floor/'
    | '/app/menu/'
    | '/app/roles/'
    | '/app/service/'
    | '/app/menu/products/$productId'
    | '/app/service/table/$tableId'
    | '/app/menu/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/appareil/caisse'
    | '/menu/$venueSlug'
    | '/appareil'
    | '/app/account'
    | '/app/analytics'
    | '/app/cuisine'
    | '/app/feedback'
    | '/app/onboarding'
    | '/app/rapport'
    | '/app/team'
    | '/auth/otp'
    | '/invitation/$token'
    | '/api/auth/$'
    | '/appareil/table/$tableId'
    | '/r/$venueSlug/indisponible'
    | '/r/$venueSlug/table'
    | '/app'
    | '/app/floor/print'
    | '/app/menu/availability'
    | '/app/menu/categories'
    | '/app/menu/options'
    | '/app/roles/$roleId'
    | '/app/service/caisse'
    | '/app/settings/devices'
    | '/app/settings/payments'
    | '/app/settings/stations'
    | '/app/settings/venue'
    | '/r/$venueSlug/t/$token'
    | '/app/floor'
    | '/app/menu'
    | '/app/roles'
    | '/app/service'
    | '/app/menu/products/$productId'
    | '/app/service/table/$tableId'
    | '/app/menu/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/appareil'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/app'
    | '/_auth/connexion'
    | '/api/client-errors'
    | '/api/health'
    | '/appareil/caisse'
    | '/menu/$venueSlug'
    | '/appareil/'
    | '/_auth/app/account'
    | '/_auth/app/analytics'
    | '/_auth/app/cuisine'
    | '/_auth/app/feedback'
    | '/_auth/app/menu'
    | '/_auth/app/onboarding'
    | '/_auth/app/rapport'
    | '/_auth/app/service'
    | '/_auth/app/team'
    | '/_auth/auth/otp'
    | '/_auth/invitation/$token'
    | '/api/auth/$'
    | '/appareil/table/$tableId'
    | '/r/$venueSlug/indisponible'
    | '/r/$venueSlug/table'
    | '/_auth/app/'
    | '/_auth/app/floor/print'
    | '/_auth/app/menu/availability'
    | '/_auth/app/menu/categories'
    | '/_auth/app/menu/options'
    | '/_auth/app/roles/$roleId'
    | '/_auth/app/service/caisse'
    | '/_auth/app/settings/devices'
    | '/_auth/app/settings/payments'
    | '/_auth/app/settings/stations'
    | '/_auth/app/settings/venue'
    | '/r/$venueSlug/t/$token'
    | '/_auth/app/floor/'
    | '/_auth/app/menu/'
    | '/_auth/app/roles/'
    | '/_auth/app/service/'
    | '/_auth/app/menu/products/$productId'
    | '/_auth/app/service/table/$tableId'
    | '/_auth/app/menu/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppareilRoute: typeof AppareilRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiClientErrorsRoute: typeof ApiClientErrorsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  MenuVenueSlugRoute: typeof MenuVenueSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RVenueSlugIndisponibleRoute: typeof RVenueSlugIndisponibleRoute
  RVenueSlugTableRoute: typeof RVenueSlugTableRoute
  RVenueSlugTTokenRoute: typeof RVenueSlugTTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appareil': {
      id: '/appareil'
      path: '/appareil'
      fullPath: '/appareil'
      preLoaderRoute: typeof AppareilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/connexion': {
      id: '/_auth/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/client-errors': {
      id: '/api/client-errors'
      path: '/api/client-errors'
      fullPath: '/api/client-errors'
      preLoaderRoute: typeof ApiClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appareil/': {
      id: '/appareil/'
      path: '/'
      fullPath: '/appareil/'
      preLoaderRoute: typeof AppareilIndexRouteImport
      parentRoute: typeof AppareilRoute
    }
    '/appareil/caisse': {
      id: '/appareil/caisse'
      path: '/caisse'
      fullPath: '/appareil/caisse'
      preLoaderRoute: typeof AppareilCaisseRouteImport
      parentRoute: typeof AppareilRoute
    }
    '/menu/$venueSlug': {
      id: '/menu/$venueSlug'
      path: '/menu/$venueSlug'
      fullPath: '/menu/$venueSlug'
      preLoaderRoute: typeof MenuVenueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/account': {
      id: '/_auth/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthAppAccountRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/analytics': {
      id: '/_auth/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthAppAnalyticsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/cuisine': {
      id: '/_auth/app/cuisine'
      path: '/cuisine'
      fullPath: '/app/cuisine'
      preLoaderRoute: typeof AuthAppCuisineRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/feedback': {
      id: '/_auth/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AuthAppFeedbackRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/menu': {
      id: '/_auth/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AuthAppMenuRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/onboarding': {
      id: '/_auth/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthAppOnboardingRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/rapport': {
      id: '/_auth/app/rapport'
      path: '/rapport'
      fullPath: '/app/rapport'
      preLoaderRoute: typeof AuthAppRapportRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/service': {
      id: '/_auth/app/service'
      path: '/service'
      fullPath: '/app/service'
      preLoaderRoute: typeof AuthAppServiceRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/team': {
      id: '/_auth/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthAppTeamRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/auth/otp': {
      id: '/_auth/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthAuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invitation/$token': {
      id: '/_auth/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof AuthInvitationTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appareil/table/$tableId': {
      id: '/appareil/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/appareil/table/$tableId'
      preLoaderRoute: typeof AppareilTableTableIdRouteImport
      parentRoute: typeof AppareilRoute
    }
    '/r/$venueSlug/indisponible': {
      id: '/r/$venueSlug/indisponible'
      path: '/r/$venueSlug/indisponible'
      fullPath: '/r/$venueSlug/indisponible'
      preLoaderRoute: typeof RVenueSlugIndisponibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$venueSlug/table': {
      id: '/r/$venueSlug/table'
      path: '/r/$venueSlug/table'
      fullPath: '/r/$venueSlug/table'
      preLoaderRoute: typeof RVenueSlugTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/floor/': {
      id: '/_auth/app/floor/'
      path: '/floor'
      fullPath: '/app/floor/'
      preLoaderRoute: typeof AuthAppFloorIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/floor/print': {
      id: '/_auth/app/floor/print'
      path: '/floor/print'
      fullPath: '/app/floor/print'
      preLoaderRoute: typeof AuthAppFloorPrintRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/menu/': {
      id: '/_auth/app/menu/'
      path: '/'
      fullPath: '/app/menu/'
      preLoaderRoute: typeof AuthAppMenuIndexRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/menu/availability': {
      id: '/_auth/app/menu/availability'
      path: '/availability'
      fullPath: '/app/menu/availability'
      preLoaderRoute: typeof AuthAppMenuAvailabilityRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/menu/categories': {
      id: '/_auth/app/menu/categories'
      path: '/categories'
      fullPath: '/app/menu/categories'
      preLoaderRoute: typeof AuthAppMenuCategoriesRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/menu/options': {
      id: '/_auth/app/menu/options'
      path: '/options'
      fullPath: '/app/menu/options'
      preLoaderRoute: typeof AuthAppMenuOptionsRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/roles/': {
      id: '/_auth/app/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AuthAppRolesIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/roles/$roleId': {
      id: '/_auth/app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/app/roles/$roleId'
      preLoaderRoute: typeof AuthAppRolesRoleIdRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/service/': {
      id: '/_auth/app/service/'
      path: '/'
      fullPath: '/app/service/'
      preLoaderRoute: typeof AuthAppServiceIndexRouteImport
      parentRoute: typeof AuthAppServiceRoute
    }
    '/_auth/app/service/caisse': {
      id: '/_auth/app/service/caisse'
      path: '/caisse'
      fullPath: '/app/service/caisse'
      preLoaderRoute: typeof AuthAppServiceCaisseRouteImport
      parentRoute: typeof AuthAppServiceRoute
    }
    '/_auth/app/settings/devices': {
      id: '/_auth/app/settings/devices'
      path: '/settings/devices'
      fullPath: '/app/settings/devices'
      preLoaderRoute: typeof AuthAppSettingsDevicesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/settings/payments': {
      id: '/_auth/app/settings/payments'
      path: '/settings/payments'
      fullPath: '/app/settings/payments'
      preLoaderRoute: typeof AuthAppSettingsPaymentsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/settings/stations': {
      id: '/_auth/app/settings/stations'
      path: '/settings/stations'
      fullPath: '/app/settings/stations'
      preLoaderRoute: typeof AuthAppSettingsStationsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/settings/venue': {
      id: '/_auth/app/settings/venue'
      path: '/settings/venue'
      fullPath: '/app/settings/venue'
      preLoaderRoute: typeof AuthAppSettingsVenueRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/r/$venueSlug/t/$token': {
      id: '/r/$venueSlug/t/$token'
      path: '/r/$venueSlug/t/$token'
      fullPath: '/r/$venueSlug/t/$token'
      preLoaderRoute: typeof RVenueSlugTTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/menu/products/': {
      id: '/_auth/app/menu/products/'
      path: '/products'
      fullPath: '/app/menu/products/'
      preLoaderRoute: typeof AuthAppMenuProductsIndexRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/menu/products/$productId': {
      id: '/_auth/app/menu/products/$productId'
      path: '/products/$productId'
      fullPath: '/app/menu/products/$productId'
      preLoaderRoute: typeof AuthAppMenuProductsProductIdRouteImport
      parentRoute: typeof AuthAppMenuRoute
    }
    '/_auth/app/service/table/$tableId': {
      id: '/_auth/app/service/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/app/service/table/$tableId'
      preLoaderRoute: typeof AuthAppServiceTableTableIdRouteImport
      parentRoute: typeof AuthAppServiceRoute
    }
  }
}

interface AuthAppMenuRouteChildren {
  AuthAppMenuAvailabilityRoute: typeof AuthAppMenuAvailabilityRoute
  AuthAppMenuCategoriesRoute: typeof AuthAppMenuCategoriesRoute
  AuthAppMenuOptionsRoute: typeof AuthAppMenuOptionsRoute
  AuthAppMenuIndexRoute: typeof AuthAppMenuIndexRoute
  AuthAppMenuProductsProductIdRoute: typeof AuthAppMenuProductsProductIdRoute
  AuthAppMenuProductsIndexRoute: typeof AuthAppMenuProductsIndexRoute
}

const AuthAppMenuRouteChildren: AuthAppMenuRouteChildren = {
  AuthAppMenuAvailabilityRoute: AuthAppMenuAvailabilityRoute,
  AuthAppMenuCategoriesRoute: AuthAppMenuCategoriesRoute,
  AuthAppMenuOptionsRoute: AuthAppMenuOptionsRoute,
  AuthAppMenuIndexRoute: AuthAppMenuIndexRoute,
  AuthAppMenuProductsProductIdRoute: AuthAppMenuProductsProductIdRoute,
  AuthAppMenuProductsIndexRoute: AuthAppMenuProductsIndexRoute,
}

const AuthAppMenuRouteWithChildren = AuthAppMenuRoute._addFileChildren(
  AuthAppMenuRouteChildren,
)

interface AuthAppServiceRouteChildren {
  AuthAppServiceCaisseRoute: typeof AuthAppServiceCaisseRoute
  AuthAppServiceIndexRoute: typeof AuthAppServiceIndexRoute
  AuthAppServiceTableTableIdRoute: typeof AuthAppServiceTableTableIdRoute
}

const AuthAppServiceRouteChildren: AuthAppServiceRouteChildren = {
  AuthAppServiceCaisseRoute: AuthAppServiceCaisseRoute,
  AuthAppServiceIndexRoute: AuthAppServiceIndexRoute,
  AuthAppServiceTableTableIdRoute: AuthAppServiceTableTableIdRoute,
}

const AuthAppServiceRouteWithChildren = AuthAppServiceRoute._addFileChildren(
  AuthAppServiceRouteChildren,
)

interface AuthAppRouteChildren {
  AuthAppAccountRoute: typeof AuthAppAccountRoute
  AuthAppAnalyticsRoute: typeof AuthAppAnalyticsRoute
  AuthAppCuisineRoute: typeof AuthAppCuisineRoute
  AuthAppFeedbackRoute: typeof AuthAppFeedbackRoute
  AuthAppMenuRoute: typeof AuthAppMenuRouteWithChildren
  AuthAppOnboardingRoute: typeof AuthAppOnboardingRoute
  AuthAppRapportRoute: typeof AuthAppRapportRoute
  AuthAppServiceRoute: typeof AuthAppServiceRouteWithChildren
  AuthAppTeamRoute: typeof AuthAppTeamRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppFloorPrintRoute: typeof AuthAppFloorPrintRoute
  AuthAppRolesRoleIdRoute: typeof AuthAppRolesRoleIdRoute
  AuthAppSettingsDevicesRoute: typeof AuthAppSettingsDevicesRoute
  AuthAppSettingsPaymentsRoute: typeof AuthAppSettingsPaymentsRoute
  AuthAppSettingsStationsRoute: typeof AuthAppSettingsStationsRoute
  AuthAppSettingsVenueRoute: typeof AuthAppSettingsVenueRoute
  AuthAppFloorIndexRoute: typeof AuthAppFloorIndexRoute
  AuthAppRolesIndexRoute: typeof AuthAppRolesIndexRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppAccountRoute: AuthAppAccountRoute,
  AuthAppAnalyticsRoute: AuthAppAnalyticsRoute,
  AuthAppCuisineRoute: AuthAppCuisineRoute,
  AuthAppFeedbackRoute: AuthAppFeedbackRoute,
  AuthAppMenuRoute: AuthAppMenuRouteWithChildren,
  AuthAppOnboardingRoute: AuthAppOnboardingRoute,
  AuthAppRapportRoute: AuthAppRapportRoute,
  AuthAppServiceRoute: AuthAppServiceRouteWithChildren,
  AuthAppTeamRoute: AuthAppTeamRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppFloorPrintRoute: AuthAppFloorPrintRoute,
  AuthAppRolesRoleIdRoute: AuthAppRolesRoleIdRoute,
  AuthAppSettingsDevicesRoute: AuthAppSettingsDevicesRoute,
  AuthAppSettingsPaymentsRoute: AuthAppSettingsPaymentsRoute,
  AuthAppSettingsStationsRoute: AuthAppSettingsStationsRoute,
  AuthAppSettingsVenueRoute: AuthAppSettingsVenueRoute,
  AuthAppFloorIndexRoute: AuthAppFloorIndexRoute,
  AuthAppRolesIndexRoute: AuthAppRolesIndexRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
  AuthConnexionRoute: typeof AuthConnexionRoute
  AuthAuthOtpRoute: typeof AuthAuthOtpRoute
  AuthInvitationTokenRoute: typeof AuthInvitationTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
  AuthConnexionRoute: AuthConnexionRoute,
  AuthAuthOtpRoute: AuthAuthOtpRoute,
  AuthInvitationTokenRoute: AuthInvitationTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppareilRouteChildren {
  AppareilCaisseRoute: typeof AppareilCaisseRoute
  AppareilIndexRoute: typeof AppareilIndexRoute
  AppareilTableTableIdRoute: typeof AppareilTableTableIdRoute
}

const AppareilRouteChildren: AppareilRouteChildren = {
  AppareilCaisseRoute: AppareilCaisseRoute,
  AppareilIndexRoute: AppareilIndexRoute,
  AppareilTableTableIdRoute: AppareilTableTableIdRoute,
}

const AppareilRouteWithChildren = AppareilRoute._addFileChildren(
  AppareilRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppareilRoute: AppareilRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiClientErrorsRoute: ApiClientErrorsRoute,
  ApiHealthRoute: ApiHealthRoute,
  MenuVenueSlugRoute: MenuVenueSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RVenueSlugIndisponibleRoute: RVenueSlugIndisponibleRoute,
  RVenueSlugTableRoute: RVenueSlugTableRoute,
  RVenueSlugTTokenRoute: RVenueSlugTTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
